# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "TimeTemp"
email:
description: >-
  Time and temperature graphs of phant data using google chart JS
  libraries. SFE Phant service is no longer in production but docker
  containers, kubernetes and Raspbery Pi-s can substitute.
twitter_username: idcrook
github_username: idcrook
#minimal_mistakes_skin: default
minimal_mistakes_skin: contrast
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Denver # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "David Crook"
  avatar : # "/assets/images/bio-photo.jpg"
  bio    : "TimeTemp charts"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/idcrook/timetemp"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/idcrook"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

# head_scripts:
#   - https://code.jquery.com/jquery-3.3.1.min.js
#   - /assets/js/your-custom-head-script.js
# footer_scripts:
#   - /assets/js/your-custom-footer-script.js
after_footer_scripts:
  # needs to be loaded _after_ jQuery (which is done in main.min.js in footer_scripts)
  # FIXME: copy jquery-csv to local assets
  - https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/1.0.5/jquery.csv.js


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # author_profile: true
      # read_time: true
      # comments: true
      # share: true
      # related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
